name: example_meme_generator
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.3+1
  path_provider: ^1.6.21
  image_gallery_saver: ^1.2.2
  permission_handler: ^4.2.0+hotfix.3
  image_size_getter: ^0.1.0
  google_fonts: ^1.1.1
  cupertino_icons: ^0.1.2
  auto_size_text: 2.1.0
  image_cropper: ^1.3.1
  gallery_saver: ^2.0.1
  dio:

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/
  #  - images/a_dot_ham.jpeg